import DashBoardMe from "@/components/DashboardMe/DashBoardMe";
import React from "react";
export const metadata = {
  title: "Me - Oyolloo",
  description: "Generated by create next app",
};
const MePage = () => {
  return <DashBoardMe />;
};

export default MePage;
