import SignIn from "@/components/SignIn/SignIn";
export const metadata = {
  title: "Sign In - Oyolloo",
  description: "Generated by create next app",
};

const SignInPage = () => {
  return <SignIn />;
};

export default SignInPage;
