import SignIn from "@/app/components/SignIn/SignIn";
export const metadata = {
  title: "Sign In - Oyolloo Hr",
  description: "Generated by create next app",
};

const SignInPage = () => {
  return <SignIn />;
};

export default SignInPage;
