import Directory from "@/components/Administrator/Directory/Directory";
import React from "react";
export const metadata = {
  title: "Directory - Oyolloo",
  description: "Generated by create next app",
};

const DirectoryPage = () => {
  return <Directory />;
};

export default DirectoryPage;
