import DashboardProfile from "@/components/DashboardProfile/DashboardProfile";

export const metadata = {
  title: "Profile - Oyolloo",
  description: "Generated by create next app",
};

const ProfilePage = () => {
  return <></>;
};

export default ProfilePage;
