import DashboardProfile from "@/app/components/DashboardProfile/DashboardProfile";

export const metadata = {
  title: "Profile - Oyolloo HR",
  description: "Generated by create next app",
};

const ProfilePage = () => {
  return <DashboardProfile />;
};

export default ProfilePage;
