import AccountEdit from "@/app/components/AccountEdit/AccountEdit";
export const metadata = {
  title: "Account - Oyolloo HR",
  description: "Generated by create next app",
};
const AccountEditPage = () => {
  return <AccountEdit />;
};

export default AccountEditPage;
