import { Inter } from "next/font/google";
import "./globals.css";
import * as React from "react";
import HrProvider from "@/context/HrProvider";
import Layout from "./components/Layout/Layout";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/oyolloo.png", // /public path
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <head>
        <link rel='icon' href='/oyolloo.png' type='image/png' sizes='32x32' />
      </head>
      <body className={inter.className}>
        <HrProvider>
          <Layout>{children}</Layout>
        </HrProvider>
      </body>
    </html>
  );
}
