import Deparments from "@/components/Settings/Core/Departments/Deparments";
export const metadata = {
  title: "Departments - Oyolloo",
  description: "Generated by create next app",
};

const DepartmentPage = () => {
  return <Deparments />;
};

export default DepartmentPage;
