import Designations from "@/components/Settings/Core/Designations/Designations";
export const metadata = {
  title: "Designations - Oyolloo",
  description: "Generated by create next app",
};
const DesignationsPage = () => {
  return <Designations />;
};

export default DesignationsPage;
