import React from "react";
export const metadata = {
  title: "Settings - Oyolloo",
  description: "Generated by create next app",
};

const layout = ({ children }) => {
  return children;
};

export default layout;
