import DashboardHome from "@/components/DashboardHome/DashboardHome";

export const metadata = {
  title: "Dashboard - Oyolloo",
  description: "Generated by create next app",
};

const DashboardPage = () => {
  return <DashboardHome />;
};

export default DashboardPage;
