import React from "react";
// import Chart from "../components/Chart/Chart";
export const metadata = {
  title: "Dashboard - Oyolloo HR",
  description: "Generated by create next app",
};

const DashboardPage = () => {
  return (
    <div>
      <h1>Home</h1>
    </div>
  );
};

export default DashboardPage;
