import DashboardHome from "../components/DashboardHome/DashboardHome";

// import Chart from "../components/Chart/Chart";
export const metadata = {
  title: "Dashboard - Oyolloo HR",
  description: "Generated by create next app",
};

const DashboardPage = () => {
  return <DashboardHome />;
};

export default DashboardPage;
