import Skills from "@/components/Settings/Core/Skills/Skills";
import React from "react";
export const metadata = {
  title: "Skills - Oyolloo",
  description: "Generated by create next app",
};

const SkillsPage = () => {
  return <Skills />;
};

export default SkillsPage;
